wdci-dev/RIO-Education-Metadata

- unpackaged/post/12_appointment_scheduler_automation/email/rio_ed__RIO_Education/RIO_Education_Appointment_new_appointment.email
- unpackaged/post/12_appointment_scheduler_automation/email/rio_ed__RIO_Education/RIO_Education_Appointment_new_appointment.email-meta.xml
- unpackaged/post/12_appointment_scheduler_automation/email/rio_ed__RIO_Education/RIO_Education_Appointment_status_updated.email
- unpackaged/post/12_appointment_scheduler_automation/email/rio_ed__RIO_Education/RIO_Education_Appointment_status_updated.email-meta.xml
> Namespace fix

- cumulusci.yml
> Added v3.10 to installer

- cumulusci.yml
> Added 3.10.1 to installer

- cumulusci.yml
> Added v3.10.2

- cumulusci.yml
> Added 3.10.3 to installer

- unpackaged/config/ready/15_Calls/classes/redu_GRD_SubGradeToGradeRollup_TEST.cls
> Update to redu_GRD_SubGradeToGradeRollup_TEST

- unpackaged/config/ready/15_Calls/package.xml
> Added Admin profile to RIO Ready Calls package.xml

- unpackaged/config/ready/15_Calls/profiles/Admin.profile
> Updates to RIO Ready Calls Admin.profile

- unpackaged/config/ready/15_Calls/flows/REDU_Course_Connection_Call_Count_Max.flow-meta.xml
- unpackaged/config/ready/15_Calls/flows/REDU_Term_Grade_Increment_Course_Connection_Call_Number.flow-meta.xml
- unpackaged/config/ready/15_Calls/objects/hed__Course_Enrollment__c.object
> Updates to RIO Ready Calls

- unpackaged/config/ready/15_Calls/flows/REDU_Course_Connection_Call_Count_Max.flow-meta.xml
- unpackaged/config/ready/15_Calls/flows/REDU_Term_Grade_Increment_Course_Connection_Call_Number.flow-meta.xml
- unpackaged/config/ready/15_Calls/package.xml
> Fixed issues with RIO Ready Calls

- cumulusci.yml
> UI name for 02_heda_object_activity

- apex/approve_fs.txt
- apex/deactivate_community_users.txt
- apex/delete_sample_data.txt
- apex/plan_line_session_ids.txt
> Removed RIO P1 field from all queries

- cumulusci.yml
> Added v3.11.2

- cumulusci.yml
> Added version to install_managed task

- cumulusci.yml
> Added v3.11.3

- cumulusci.yml
> v3.11.3 version number

- cumulusci.yml
> Added v3.11.4

- unpackaged/post/02_eda_objects_ui/objects/hed__Address__c.object
> Removed startsWith attribute from Address object

- cumulusci.yml
> v3.11.5 release

- cumulusci.yml
> Added v3.11.6

- cumulusci.yml
> Added v3.11.7

- unpackaged/post/08_redu_object_tracking/objects/rio_ed__PE_Pathway_Status__c.object
> update gpa precision

- cumulusci.yml
> Added new preflight check for community plan

- cumulusci.yml
> Fixed typo

- apex/check_tc_course_id.txt
- cumulusci.yml
> Added check_tc_course_id Apex script

- apex/check_tc_course_id.txt
- metadeploy/labels_en.json
> Fixed check_tc_course_id script

- apex/check_tc_course_id.txt
> Used custom exception in check_tc_course_id

- apex/check_tc_course_id.txt
> Fixed typo in check_tc_course_id error message

- apex/check_tc_course_id.txt
> Fixed typo in check_tc_course_id

- apex/check_tc_course_id.txt
> Fixed check_tc_course_id

- cumulusci.yml
> Updated EDA pre-flight check

- apex/check_tc_course_id.txt
> Check for presence of Approved Course field in check_tc_course_id script

- .gitignore
- apex/check_tc_course_id.txt
> Check tc course

- apex/check_tc_course_id.txt
- metadeploy/labels_en.json
> Check for existence of Transfer Credit object in check_tc_course_id

- datasets/sample.sql
> Set sample data fee schedules to draft

- apex/booking_session_time_ids.txt
> Fixed bug in booking_session_time_ids

- apex/provision_community_users.txt
> Fixed typos in provision_community_users script

- apex/provision_community_users.txt
> Reverted provision_community_users script changes

- apex/provision_community_users.txt
> Added provision_community_users changes back

- cumulusci.yml
> Made booking session id script optional for testing

- cumulusci.yml
> Made booking_session_time_ids task required

- datasets/sample.sql
> Set fee schedules to draft

- cumulusci.yml
- metadeploy/labels_en.json
> Fix for check_lws_enabled

- cumulusci.yml
> Added dev_install plan

- cumulusci.yml
> Set dev_install plan to addditional

- cumulusci.yml
- metadeploy/labels_en.json
> Made deploy_pre for dev_install optional

- cumulusci.yml
> Made Check Transfer Credit Course ID in dev_install required

- cumulusci.yml
- metadeploy/labels_en.json
> Added UI options for community profile tasks

- cumulusci.yml
> Added v3.12.1

- cumulusci.yml
> Changed dev_install plan to metadata plan

- cumulusci.yml
> Check for EDA not RIO Ed in metadata plan pre-flight check

- cumulusci.yml
> v3.13.1 release

- unpackaged/config/community/01_redu_student_profile/profiles/REDU - Student.profile
- unpackaged/config/community/02_redu_faculty_profile/profiles/REDU - Faculty.profile
> Added RIOEducation Community Announcement Layout assignments

- unpackaged/config/community/01_redu_student_profile/profiles/REDU - Student.profile
- unpackaged/config/community/02_redu_faculty_profile/profiles/REDU - Faculty.profile
> Removed 3.14 specific layout assignments

- unpackaged/post/08_redu_object_tracking/package.xml
> Update package.xml version for REDU Object Tracking

- unpackaged/config/community/01_redu_student_profile/profiles/REDU - Student.profile
> Fixed name of RIOEducation Community Registration Layout

- cumulusci.yml
> Added v3.14.1

- apex/assignRole.txt
- apex/postInstallation.txt
- cumulusci.yml
> Automated some scratch org setup tasks

- apex/postInstallation.txt
> Removed private post install methods

- apex/update_group_members.txt
- cumulusci.yml
> Various updates

- apex/update_group_members.txt
> update_group_members fix

- cumulusci.yml
> Added v3.14.2

- cumulusci.yml
> Added v3.14.3 to installer

- cumulusci.yml
> Make HEDA Object Tracking optional

- cumulusci.yml
> Remove dependencies flow

- cumulusci.yml
> 3.14.3 test

- cumulusci.yml
> Made deploy_pre tasks required

- cumulusci.yml
> Added collision check option

- cumulusci.yml
> Removed collision check option

- cumulusci.yml
- metadeploy/labels_en.json
> 3.15 install step UI name

- cumulusci.yml
> Added v3.15.1 to installer

- cumulusci.yml
> Added v3.15.2

- cumulusci.yml
> Added v3.17

- cumulusci.yml
> Add v3.18.1

- cumulusci.yml
> Added v3.18.2

- cumulusci.yml
> Added v3.18.4 to installer

- unpackaged/post/08_redu_object_tracking/objects/rio_ed__Session_Connection__c.object
> V3.20 ISS-002539
